# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values

title: Jared Rigby
email: talk@jaredrigby.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Computer scientist exploring the world of the web, 
  cybersecurity and physical computing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jazibobs
github_username:  jazibobs

# Build settings
# theme: jgr-theme

collections:
  cs_resources:
    output: true
    permalink: /cs/:path
    sort_by: syllabus
  hacking:
    output: true
    permalink: /hacking/:path
  projects:
    output: true
    permalink: /projects/:path

plugins:
  - jekyll-feed

sass:
    sass_dir: _sass

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/