# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jared Rigby
subtitle: Freelance Web Developer
description: > # this means to ignore newlines until "baseurl:"
  Freelance web developer interested in the web, frontend, design, tech, linux, JavaScript and WordPress
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.jaredrigby.co.uk" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
